language: python

python:
  - "3.7"
  dist: xenial
  sudo: true
  - "nightly"
# command to install dependencies
install:
  - "pip install pytest"
  - "pip install -r requirements.txt"
# command to run tests
script: python -m pytest section3/video_code/